services:
  jenkins:
    build:
      context: .
      dockerfile: .docker/Jenkins/Dockerfile
    image: jenkins-jdk-17
    container_name: jenkins-jdk-17
    privileged: true
    user: root
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "D:/Dockerjenkins1:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
